import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import FirebaseAnalyticsClient from "@/components/firebase-analytics-client";
import { ChatWidget } from "@/components/chat-widget";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {/* Initialize Firebase Analytics on client only */}
        <FirebaseAnalyticsClient />
        {children}
        {/* AI Chatbot with Claude Haiku 4.5 */}
        <ChatWidget position="bottom-right" />
      </body>
    </html>
  );
}
